development:
  adapter: postgresql
  encoding: utf8
  database: sample_app_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: sample_app_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: sample_app_production
  pool: 5
  timeout: 5000