development:
  adapter: sqlite3
  database: db/development.sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000