# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 863ea9dae09a13f2f224a34f8a14d9f8b85363ffd9320c036e37d7fe6d86ea78dd9ae32a9ecdbf911fe3c2c12b2c2a838a17c5cd93936b601abb9ccb1f780cba

test:
  secret_key_base: 7066f299c31ed5d4a5d7705dda9cafc7eb96aa764d9ce156f2fddf7634d8e5032c5ee60e7a141345b0e7137a421e4e6c7e58a704d8a119a35d37630860f94bd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
